shiy:
  age: 18
server:
  port: 9766
eureka:
  instance:
    health-check-url: /actuator/health
    status-page-url-path: /actuator/info
spring:
  rabbitmq:
    host: 192.168.1.34
    port: 5672
    username: guest
    password: guest

